[functions.hash-pin]
enabled = true
verify_jwt = false
import_map = "./functions/hash-pin/deno.json"
entrypoint = "./functions/hash-pin/index.ts"

[functions.generate-supabase-token]
enabled = true
verify_jwt = false
import_map = "./functions/generate-supabase-token/deno.json"
entrypoint = "./functions/generate-supabase-token/index.ts"

[functions.send-magic-link]
enabled = true
verify_jwt = false
import_map = "./functions/send-magic-link/deno.json"
entrypoint = "./functions/send-magic-link/index.ts"

[functions.login-with-pin]
enabled = true
verify_jwt = false
import_map = "./functions/login-with-pin/deno.json"
entrypoint = "./functions/login-with-pin/index.ts"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173", "https://theedge.essateric.com"]
jwt_secret = "gFpexldf/UkH5XEfbelyjyrzTT1q1tnxxi9URC1XfVUMph+e3r76pi4BBKgNdO/Nv7ULzUYELUhg1gM84SNQGg=="


[functions.addnewstaff]
enabled = true
verify_jwt = true
import_map = "./functions/addnewstaff/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/addnewstaff/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/addnewstaff/*.html" ]

[functions.delete-staff]
enabled = true
verify_jwt = true
import_map = "./functions/delete-staff/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-staff/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-staff/*.html" ]

[functions.send-booking-emails]
enabled = true
verify_jwt = true
import_map = "./functions/send-booking-emails/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-booking-emails/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-booking-emails/*.html" ]
