[functions.hash-pin]
enabled = true
verify_jwt = false
import_map = "./functions/hash-pin/deno.json"
entrypoint = "./functions/hash-pin/index.ts"

[functions.generate-supabase-token]
enabled = true
verify_jwt = false
import_map = "./functions/generate-supabase-token/deno.json"
entrypoint = "./functions/generate-supabase-token/index.ts"

[functions.send-magic-link]
enabled = true
verify_jwt = false
import_map = "./functions/send-magic-link/deno.json"
entrypoint = "./functions/send-magic-link/index.ts"

[functions.login-with-pin]
enabled = true
verify_jwt = false
import_map = "./functions/login-with-pin/deno.json"
entrypoint = "./functions/login-with-pin/index.ts"
